import React, { useState } from "react";
import {
  ArrowUp,
  ArrowDown,
  Copy,
  Trash2,
  Sparkles,
  Settings2,
  Lock,
  Unlock,
  Plus,
  GripVertical,
  CheckCircle,
  ExternalLink,
  ChevronDown,
  ShoppingBag,
  Star,
  MousePointerClick,
  Eye,
  Sliders,
  Layers,
  Code2,
  Check,
  Zap,
  Info,
  X,
} from "lucide-react";
import { DeviceType, LanguageCode, ThemeConfig, WPBlock } from "../types";
import { translations } from "../utils/translations";

export type HoverEffectPreset = "default" | "lift" | "glow" | "zoom" | "invert";
export type HoverTargetFilter = "all" | "buttons" | "cards" | "images" | "links";

interface CanvasEditorProps {
  blocks: WPBlock[];
  selectedBlockId: string | null;
  onSelectBlock: (id: string) => void;
  onMoveBlock: (index: number, direction: "up" | "down") => void;
  onDuplicateBlock: (index: number) => void;
  onDeleteBlock: (id: string) => void;
  onInsertBlockAt: (index: number) => void;
  onAiRewriteBlock: (block: WPBlock) => void;
  device: DeviceType;
  lang: LanguageCode;
  themeConfig: ThemeConfig;
}

export const CanvasEditor: React.FC<CanvasEditorProps> = ({
  blocks,
  selectedBlockId,
  onSelectBlock,
  onMoveBlock,
  onDuplicateBlock,
  onDeleteBlock,
  onInsertBlockAt,
  onAiRewriteBlock,
  device,
  lang,
  themeConfig,
}) => {
  const t = translations[lang];
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const [hoveredDividerIndex, setHoveredDividerIndex] = useState<number | null>(null);

  // On-Hover State Simulation State
  const [isHoverSimulated, setIsHoverSimulated] = useState<boolean>(false);
  const [hoverTargetScope, setHoverTargetScope] = useState<"selected" | "all">("selected");
  const [hoverPreset, setHoverPreset] = useState<HoverEffectPreset>("default");
  const [hoverFilter, setHoverFilter] = useState<HoverTargetFilter>("all");
  const [showHoverCssModal, setShowHoverCssModal] = useState<boolean>(false);
  const [copiedCss, setCopiedCss] = useState<boolean>(false);

  // Device width mapping
  const deviceWidthClasses: Record<DeviceType, string> = {
    desktop: "w-full max-w-[1280px]",
    laptop: "w-[1024px] max-w-full",
    tablet: "w-[768px] max-w-full",
    mobile: "w-[390px] max-w-full",
    ultrawide: "w-full max-w-[1536px]",
  };

  const handleDragStart = (e: React.DragEvent, index: number) => {
    setDraggedIndex(index);
    e.dataTransfer.effectAllowed = "move";
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const handleDrop = (e: React.DragEvent, targetIndex: number) => {
    e.preventDefault();
    if (draggedIndex === null || draggedIndex === targetIndex) return;
    if (draggedIndex < targetIndex) {
      onMoveBlock(draggedIndex, "down");
    } else {
      onMoveBlock(draggedIndex, "up");
    }
    setDraggedIndex(null);
  };

  // Generate CSS preview for hover pseudo-classes
  const generateHoverCss = () => {
    const primary = themeConfig.primaryColor || "#2563eb";
    const accent = themeConfig.accentColor || "#10b981";

    let effectRules = "";
    if (hoverPreset === "lift") {
      effectRules = `  transform: translateY(-4px);\n  box-shadow: 0 20px 30px -10px rgba(79, 70, 229, 0.35);\n  border-color: ${primary};`;
    } else if (hoverPreset === "glow") {
      effectRules = `  box-shadow: 0 0 25px 2px ${primary}88, inset 0 0 15px ${primary}33;\n  border-color: ${primary};\n  filter: brightness(1.1);`;
    } else if (hoverPreset === "zoom") {
      effectRules = `  transform: scale(1.04);\n  box-shadow: 0 15px 30px rgba(0, 0, 0, 0.4);\n  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);`;
    } else if (hoverPreset === "invert") {
      effectRules = `  background-color: #ffffff;\n  color: ${primary};\n  border: 1px solid ${primary};\n  filter: contrast(1.15);`;
    } else {
      effectRules = `  transform: translateY(-2px);\n  box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.3);\n  filter: brightness(1.08);`;
    }

    return `/* WordPress Theme Hover Styles (Generated by WP Studio) */
/* Target Theme: ${themeConfig.themeName} */

/* 1. Interactive Button Hover */
.wp-block-button__link:hover,
.btn-primary:hover,
button[type="submit"]:hover {
${effectRules}
  cursor: pointer;
}

/* 2. Interactive Feature & Product Cards */
.wp-card:hover,
.woocommerce-card:hover,
.pricing-card:hover {
${effectRules}
  transition: all 0.3s ease;
}

/* 3. Media & Product Thumbnail Zoom */
.wp-block-image img:hover,
.woocommerce-card img:hover {
  transform: scale(1.06);
  filter: brightness(1.05);
  transition: transform 0.4s cubic-bezier(0.16, 1, 0.3, 1);
}

/* 4. Navigation & Hyperlinks Hover */
.nav-link:hover,
.wp-block-navigation-item a:hover {
  color: ${accent} !important;
  text-decoration: underline;
  text-underline-offset: 4px;
}`;
  };

  const handleCopyCss = () => {
    navigator.clipboard.writeText(generateHoverCss());
    setCopiedCss(true);
    setTimeout(() => setCopiedCss(false), 2000);
  };

  return (
    <main className="flex-1 h-full canvas-bento-grid overflow-y-auto overflow-x-hidden flex flex-col items-center py-5 px-4 select-none relative">
      {/* Top Controls: Device Preview Indicator & On-Hover Simulation Tool Bar */}
      <div className="w-full max-w-[1280px] mb-4 flex flex-wrap items-center justify-between gap-3">
        {/* Device frame header indicator */}
        <div className="flex items-center gap-2.5 px-4 py-1.5 rounded-full bg-[#121217] border border-white/[0.08] text-xs text-zinc-300 font-mono shadow-sm">
          <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
          <span className="uppercase font-bold text-zinc-200">{device} Preview</span>
          <span className="text-zinc-600">•</span>
          <span className="text-zinc-400">
            {device === "mobile"
              ? "390 × 844 px"
              : device === "tablet"
              ? "768 × 1024 px"
              : device === "laptop"
              ? "1024 × 768 px"
              : device === "ultrawide"
              ? "1536 × 960 px"
              : "1280 × 800 px"}
          </span>
        </div>

        {/* 'On-Hover' State Simulation Control Widget */}
        <div className="flex items-center gap-2 bg-[#121217] border border-white/[0.1] rounded-2xl p-1.5 shadow-lg backdrop-blur-md">
          {/* Main Hover Toggle Switch */}
          <button
            onClick={() => setIsHoverSimulated((prev) => !prev)}
            title="Bật/Tắt chế độ mô phỏng trạng thái :hover tương tác cho các khối"
            className={`flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
              isHoverSimulated
                ? "bg-gradient-to-r from-amber-500 to-indigo-600 text-white shadow-md shadow-indigo-600/30 ring-2 ring-amber-400/40"
                : "bg-[#181822] text-zinc-400 hover:text-zinc-100 hover:bg-white/[0.06] border border-white/[0.04]"
            }`}
          >
            <MousePointerClick
              className={`w-3.5 h-3.5 ${isHoverSimulated ? "animate-bounce text-amber-200" : "text-zinc-400"}`}
            />
            <span>Mô Phỏng :hover</span>
            <span
              className={`text-[9px] px-1.5 py-0.5 rounded font-mono font-bold tracking-wider ${
                isHoverSimulated
                  ? "bg-amber-400 text-zinc-950 font-black"
                  : "bg-white/[0.06] text-zinc-400"
              }`}
            >
              {isHoverSimulated ? "ON" : "OFF"}
            </span>
          </button>

          {/* Hover Simulation Options (Active when simulation is enabled) */}
          {isHoverSimulated && (
            <>
              <div className="h-5 w-px bg-white/[0.1] mx-0.5" />

              {/* Scope Selector: Selected Block vs All */}
              <div className="flex items-center bg-[#0A0A0C] p-0.5 rounded-xl border border-white/[0.06]">
                <button
                  onClick={() => setHoverTargetScope("selected")}
                  className={`px-2.5 py-1 rounded-lg text-[11px] font-semibold transition-all ${
                    hoverTargetScope === "selected"
                      ? "bg-indigo-600 text-white shadow-sm"
                      : "text-zinc-400 hover:text-zinc-200"
                  }`}
                  title="Chỉ mô phỏng hiệu ứng hover cho khối giao diện đang được chọn"
                >
                  Khối Chọn
                </button>
                <button
                  onClick={() => setHoverTargetScope("all")}
                  className={`px-2.5 py-1 rounded-lg text-[11px] font-semibold transition-all ${
                    hoverTargetScope === "all"
                      ? "bg-indigo-600 text-white shadow-sm"
                      : "text-zinc-400 hover:text-zinc-200"
                  }`}
                  title="Mô phỏng hiệu ứng hover trên tất cả các khối trong trang"
                >
                  Tất Cả
                </button>
              </div>

              {/* Hover Effect Preset Selector */}
              <div className="flex items-center gap-1">
                <span className="text-[10px] text-zinc-400 font-medium pl-1 hidden sm:inline">Kiểu:</span>
                <select
                  value={hoverPreset}
                  onChange={(e) => setHoverPreset(e.target.value as HoverEffectPreset)}
                  className="bg-[#0A0A0C] border border-white/[0.1] text-zinc-200 text-[11px] font-medium rounded-xl px-2 py-1 focus:outline-none focus:border-indigo-500 cursor-pointer"
                >
                  <option value="default">Mặc Định (Default)</option>
                  <option value="lift">Nâng Khối (Lift & Shadow)</option>
                  <option value="glow">Phát Sáng (Neon Glow)</option>
                  <option value="zoom">Phóng To (Zoom & Scale)</option>
                  <option value="invert">Đảo Màu (Invert Contrast)</option>
                </select>
              </div>

              {/* Target Element Filter Selector */}
              <div className="flex items-center gap-1 hidden md:flex">
                <span className="text-[10px] text-zinc-400 font-medium pl-1">Phần tử:</span>
                <select
                  value={hoverFilter}
                  onChange={(e) => setHoverFilter(e.target.value as HoverTargetFilter)}
                  className="bg-[#0A0A0C] border border-white/[0.1] text-zinc-200 text-[11px] font-medium rounded-xl px-2 py-1 focus:outline-none focus:border-indigo-500 cursor-pointer"
                >
                  <option value="all">Tất cả phần tử</option>
                  <option value="buttons">Nút bấm (Buttons)</option>
                  <option value="cards">Thẻ (Cards)</option>
                  <option value="images">Hình ảnh (Images)</option>
                  <option value="links">Liên kết (Links)</option>
                </select>
              </div>

              {/* View CSS Code Snippet Button */}
              <button
                onClick={() => setShowHoverCssModal(true)}
                title="Xem và sao chép mã CSS :hover đã tạo"
                className="p-1.5 text-zinc-400 hover:text-indigo-300 rounded-xl hover:bg-white/[0.06] transition-colors"
              >
                <Code2 className="w-4 h-4" />
              </button>
            </>
          )}
        </div>
      </div>

      {/* Floating Active Simulation Banner when Hover is ON */}
      {isHoverSimulated && (
        <div className="w-full max-w-[1280px] mb-3 px-4 py-2 rounded-2xl bg-gradient-to-r from-amber-500/10 via-indigo-500/15 to-purple-500/10 border border-amber-500/30 flex items-center justify-between text-xs text-amber-200 animate-in fade-in slide-in-from-top-2">
          <div className="flex items-center gap-2.5">
            <span className="relative flex h-2.5 w-2.5">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-amber-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-amber-500"></span>
            </span>
            <span className="font-bold text-amber-300">Đang mô phỏng trạng thái On-Hover (:hover)</span>
            <span className="text-zinc-500">•</span>
            <span className="text-zinc-300 text-[11px]">
              Phạm vi:{" "}
              <strong className="text-white">
                {hoverTargetScope === "selected" ? "Khối được chọn" : "Toàn bộ giao diện"}
              </strong>{" "}
              | Hiệu ứng: <strong className="text-white uppercase">{hoverPreset}</strong>
            </span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowHoverCssModal(true)}
              className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-indigo-600/30 hover:bg-indigo-600/50 text-indigo-200 border border-indigo-500/30 text-[11px] font-semibold transition-colors"
            >
              <Code2 className="w-3 h-3" />
              <span>Xem CSS Hover</span>
            </button>
            <button
              onClick={() => setIsHoverSimulated(false)}
              className="p-1 text-zinc-400 hover:text-zinc-100 rounded-lg hover:bg-white/[0.06]"
              title="Tắt mô phỏng hover"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      )}

      {/* Main Canvas Viewport Container */}
      <div
        className={`${deviceWidthClasses[device]} bg-[#0D0D12] rounded-3xl border border-white/[0.12] shadow-2xl overflow-hidden transition-all duration-300 min-h-[700px] flex flex-col relative`}
        style={{
          fontFamily: themeConfig.fontBody || "Inter",
        }}
      >
        {blocks.length === 0 ? (
          <div className="flex-1 flex flex-col items-center justify-center p-12 text-center space-y-4">
            <div className="w-16 h-16 rounded-2xl bg-indigo-500/15 text-indigo-400 flex items-center justify-center font-extrabold text-2xl border border-indigo-500/30 shadow-lg shadow-indigo-500/10">
              WP
            </div>
            <div className="max-w-md">
              <h3 className="text-lg font-extrabold text-zinc-100 mb-1">Canvas Hiện Đang Trống</h3>
              <p className="text-xs text-zinc-400 leading-relaxed">
                Hãy chọn một mẫu có sẵn từ thư viện hoặc kéo thả các khối bên trái để bắt đầu tạo giao diện WordPress.
              </p>
            </div>
            <button
              onClick={() => onInsertBlockAt(0)}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 via-indigo-500 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-xs font-bold text-white shadow-lg shadow-indigo-500/25 border border-indigo-400/30 transition-all"
            >
              <Plus className="w-4 h-4" />
              <span>Chèn Khối Mẫu Đầu Tiên</span>
            </button>
          </div>
        ) : (
          blocks.map((block, index) => {
            const isSelected = selectedBlockId === block.id;
            // Determine if hover effect should be applied to this block
            const shouldSimulateBlockHover =
              isHoverSimulated && (hoverTargetScope === "all" || (hoverTargetScope === "selected" && isSelected));

            return (
              <React.Fragment key={block.id}>
                {/* Insertion Divider between blocks */}
                <div
                  onMouseEnter={() => setHoveredDividerIndex(index)}
                  onMouseLeave={() => setHoveredDividerIndex(null)}
                  className="relative h-2 flex items-center justify-center group/divider z-30"
                >
                  <div
                    className={`absolute inset-x-0 h-0.5 transition-all ${
                      hoveredDividerIndex === index
                        ? "bg-indigo-500 opacity-100 scale-100"
                        : "bg-transparent opacity-0 scale-95"
                    }`}
                  />
                  {hoveredDividerIndex === index && (
                    <button
                      onClick={() => onInsertBlockAt(index)}
                      className="absolute z-40 px-3 py-1 rounded-full bg-indigo-600 text-white text-[10px] font-bold flex items-center gap-1 shadow-lg shadow-indigo-500/40 hover:scale-105 transition-transform"
                    >
                      <Plus className="w-3 h-3" />
                      <span>Chèn Khối Vào Đây</span>
                    </button>
                  )}
                </div>

                {/* The Block Wrapper */}
                <div
                  draggable
                  onDragStart={(e) => handleDragStart(e, index)}
                  onDragOver={handleDragOver}
                  onDrop={(e) => handleDrop(e, index)}
                  onClick={() => onSelectBlock(block.id)}
                  className={`relative group transition-all duration-200 cursor-pointer ${
                    isSelected
                      ? "ring-2 ring-indigo-500 ring-offset-2 ring-offset-[#0A0A0C] z-20"
                      : "hover:ring-1 hover:ring-indigo-500/40"
                  }`}
                >
                  {/* Floating Action Toolbar on Selected / Hover */}
                  <div
                    className={`absolute right-4 top-4 z-40 flex items-center gap-1 p-1 rounded-xl bg-[#121217]/95 border border-white/[0.12] backdrop-blur-xl shadow-2xl transition-all ${
                      isSelected ? "opacity-100 scale-100" : "opacity-0 group-hover:opacity-100 scale-95"
                    }`}
                    onClick={(e) => e.stopPropagation()}
                  >
                    {/* Drag Handle */}
                    <div
                      title="Kéo để đổi vị trí"
                      className="p-1.5 text-zinc-400 hover:text-zinc-100 cursor-grab active:cursor-grabbing rounded-lg hover:bg-white/[0.06]"
                    >
                      <GripVertical className="w-3.5 h-3.5" />
                    </div>

                    {/* Quick Toggle Hover Simulation for this Block */}
                    <button
                      onClick={() => {
                        if (!isSelected) onSelectBlock(block.id);
                        setIsHoverSimulated((prev) => {
                          if (!prev) {
                            setHoverTargetScope("selected");
                            return true;
                          }
                          return !prev;
                        });
                      }}
                      title={shouldSimulateBlockHover ? "Tắt mô phỏng hover cho khối này" : "Bật mô phỏng hover (:hover) cho khối này"}
                      className={`p-1.5 rounded-lg transition-colors flex items-center gap-1 text-[11px] font-bold ${
                        shouldSimulateBlockHover
                          ? "bg-amber-500/20 text-amber-300 border border-amber-500/40"
                          : "text-zinc-400 hover:text-amber-300 hover:bg-white/[0.06]"
                      }`}
                    >
                      <MousePointerClick className="w-3.5 h-3.5" />
                      <span className="text-[10px] font-mono">:hover</span>
                    </button>

                    {/* Move Up */}
                    <button
                      onClick={() => onMoveBlock(index, "up")}
                      disabled={index === 0}
                      title={t.moveUp}
                      className="p-1.5 text-zinc-400 hover:text-zinc-100 disabled:opacity-30 rounded-lg hover:bg-white/[0.06] transition-colors"
                    >
                      <ArrowUp className="w-3.5 h-3.5" />
                    </button>

                    {/* Move Down */}
                    <button
                      onClick={() => onMoveBlock(index, "down")}
                      disabled={index === blocks.length - 1}
                      title={t.moveDown}
                      className="p-1.5 text-zinc-400 hover:text-zinc-100 disabled:opacity-30 rounded-lg hover:bg-white/[0.06] transition-colors"
                    >
                      <ArrowDown className="w-3.5 h-3.5" />
                    </button>

                    {/* AI Rewrite Copy */}
                    <button
                      onClick={() => onAiRewriteBlock(block)}
                      title={t.aiRewrite}
                      className="p-1.5 text-indigo-400 hover:text-indigo-300 rounded-lg hover:bg-indigo-950/50 transition-colors"
                    >
                      <Sparkles className="w-3.5 h-3.5" />
                    </button>

                    {/* Duplicate */}
                    <button
                      onClick={() => onDuplicateBlock(index)}
                      title={t.duplicateBlock}
                      className="p-1.5 text-zinc-400 hover:text-zinc-100 rounded-lg hover:bg-white/[0.06] transition-colors"
                    >
                      <Copy className="w-3.5 h-3.5" />
                    </button>

                    {/* Delete */}
                    <button
                      onClick={() => onDeleteBlock(block.id)}
                      title={t.deleteBlock}
                      className="p-1.5 text-rose-400 hover:text-rose-300 rounded-lg hover:bg-rose-950/50 transition-colors"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  {/* Block Type Tag & Hover Status badge */}
                  <div className="absolute left-4 top-4 z-30 flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <span className="text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-lg bg-[#121217]/95 text-indigo-300 border border-indigo-500/30 shadow-md">
                      {block.name}
                    </span>
                    {shouldSimulateBlockHover && (
                      <span className="text-[10px] font-bold px-2 py-0.5 rounded-lg bg-amber-500/20 text-amber-300 border border-amber-500/30 flex items-center gap-1">
                        <MousePointerClick className="w-3 h-3" />
                        <span>:hover active</span>
                      </span>
                    )}
                  </div>

                  {/* Render Actual Block Visual Representation with Hover Simulation */}
                  <BlockRenderer
                    block={block}
                    themeConfig={themeConfig}
                    isHoverSimulated={shouldSimulateBlockHover}
                    hoverPreset={hoverPreset}
                    hoverFilter={hoverFilter}
                  />
                </div>
              </React.Fragment>
            );
          })
        )}
      </div>

      {/* Modal: CSS Hover Code Inspector */}
      {showHoverCssModal && (
        <div className="fixed inset-0 z-50 bg-[#0A0A0C]/80 backdrop-blur-md flex items-center justify-center p-4 select-none">
          <div className="w-full max-w-2xl bg-[#121217] border border-white/[0.08] rounded-3xl shadow-2xl flex flex-col overflow-hidden text-xs">
            {/* Header */}
            <div className="p-5 border-b border-white/[0.08] flex items-center justify-between bg-amber-950/20">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-amber-600/20 border border-amber-500/30 flex items-center justify-center text-amber-400">
                  <MousePointerClick className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="text-base font-bold text-zinc-100 tracking-tight">
                    Mã Nguồn CSS Trạng Thái Hover (:hover)
                  </h2>
                  <p className="text-zinc-400 text-[11px]">
                    Tự động tạo các quy tắc CSS pseudo-class tối ưu cho theme WordPress và Gutenberg
                  </p>
                </div>
              </div>

              <button
                onClick={() => setShowHoverCssModal(false)}
                className="p-2 text-zinc-400 hover:text-zinc-100 rounded-xl hover:bg-white/[0.04] transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Code Body */}
            <div className="p-6 space-y-4 bg-[#0A0A0C]">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="font-mono text-zinc-300 text-xs font-bold">style-hover.css</span>
                  <span className="text-[10px] font-semibold px-2 py-0.5 rounded-md bg-[#181822] text-amber-400 border border-amber-500/20">
                    Preset: {hoverPreset.toUpperCase()}
                  </span>
                </div>
                <button
                  onClick={handleCopyCss}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold transition-all shadow-md shadow-indigo-600/25"
                >
                  {copiedCss ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedCss ? "Đã Sao Chép!" : "Sao Chép CSS"}</span>
                </button>
              </div>

              <div className="p-4 rounded-2xl bg-[#121217] border border-white/[0.08] font-mono text-[11px] text-zinc-300 overflow-x-auto leading-relaxed max-h-[50vh]">
                <pre className="whitespace-pre">{generateHoverCss()}</pre>
              </div>

              <div className="flex items-center gap-2 p-3 rounded-xl bg-indigo-950/20 border border-indigo-500/20 text-indigo-300 text-[11px]">
                <Info className="w-4 h-4 shrink-0 text-indigo-400" />
                <span>
                  Các quy tắc này được tự động nhúng vào gói xuất mã nguồn <strong>style.css</strong> khi bạn tải về
                  hoặc xuất bản 1-Click.
                </span>
              </div>
            </div>
          </div>
        </div>
      )}
    </main>
  );
};

// Sub-component to render individual block type visuals cleanly with dynamic hover state simulation
interface BlockRendererProps {
  block: WPBlock;
  themeConfig: ThemeConfig;
  isHoverSimulated?: boolean;
  hoverPreset?: HoverEffectPreset;
  hoverFilter?: HoverTargetFilter;
}

const BlockRenderer: React.FC<BlockRendererProps> = ({
  block,
  themeConfig,
  isHoverSimulated = false,
  hoverPreset = "default",
  hoverFilter = "all",
}) => {
  const { type, content, styles } = block;

  // Helper to determine if a specific element type should display hover effect
  const isButtonHovered = isHoverSimulated && (hoverFilter === "all" || hoverFilter === "buttons");
  const isCardHovered = isHoverSimulated && (hoverFilter === "all" || hoverFilter === "cards");
  const isImageHovered = isHoverSimulated && (hoverFilter === "all" || hoverFilter === "images");
  const isLinkHovered = isHoverSimulated && (hoverFilter === "all" || hoverFilter === "links");

  // Dynamic CSS classes generator based on active preset
  const getButtonHoverClasses = (isPrimary = true) => {
    if (!isButtonHovered) return "transition-all duration-300";

    if (hoverPreset === "lift") {
      return "translate-y-[-4px] shadow-2xl shadow-indigo-500/40 ring-2 ring-indigo-400 transition-all duration-300";
    }
    if (hoverPreset === "glow") {
      return "shadow-[0_0_25px_rgba(99,102,241,0.6)] ring-2 ring-amber-400 brightness-110 transition-all duration-300";
    }
    if (hoverPreset === "zoom") {
      return "scale-105 shadow-xl transition-all duration-300";
    }
    if (hoverPreset === "invert") {
      return isPrimary
        ? "bg-white !text-indigo-900 ring-2 ring-white shadow-lg transition-all duration-300"
        : "bg-indigo-600 !text-white ring-2 ring-indigo-400 shadow-lg transition-all duration-300";
    }
    return "translate-y-[-2px] shadow-lg brightness-110 transition-all duration-300";
  };

  const getCardHoverClasses = () => {
    if (!isCardHovered) return "transition-all duration-300";

    if (hoverPreset === "lift") {
      return "translate-y-[-6px] shadow-2xl shadow-indigo-500/25 border-indigo-500/80 bg-[#181824] transition-all duration-300";
    }
    if (hoverPreset === "glow") {
      return "ring-2 ring-indigo-500/80 shadow-[0_0_30px_rgba(99,102,241,0.35)] border-indigo-400 bg-[#161622] transition-all duration-300";
    }
    if (hoverPreset === "zoom") {
      return "scale-[1.03] shadow-2xl border-indigo-500/60 bg-[#161622] transition-all duration-300";
    }
    if (hoverPreset === "invert") {
      return "border-amber-400/80 bg-[#1a1a28] shadow-xl transition-all duration-300";
    }
    return "translate-y-[-3px] border-indigo-500/60 shadow-xl bg-[#14141e] transition-all duration-300";
  };

  const getImageHoverClasses = () => {
    if (!isImageHovered) return "transition-transform duration-500";
    return "scale-105 brightness-105 filter transition-transform duration-500";
  };

  const getLinkHoverClasses = () => {
    if (!isLinkHovered) return "transition-colors";
    return "text-indigo-400 underline underline-offset-4 transition-colors font-bold";
  };

  // Header Block
  if (type === "header") {
    return (
      <header
        className={`w-full px-6 py-4 flex items-center justify-between border-b border-white/[0.08] ${
          styles.bgColor || "bg-[#0A0A0C]"
        } ${styles.textColor || "text-zinc-100"}`}
      >
        <div className="flex items-center gap-2">
          <div
            className={`w-8 h-8 rounded-xl flex items-center justify-center font-bold text-white text-sm shadow-md ${
              isButtonHovered ? "scale-105 shadow-indigo-500/30" : ""
            }`}
            style={{ backgroundColor: themeConfig.primaryColor || "#2563eb" }}
          >
            WP
          </div>
          <span className="font-extrabold text-base tracking-tight text-zinc-100">
            {content.title || "WP Studio"}
          </span>
        </div>

        <nav className="hidden md:flex items-center gap-6 text-xs font-medium text-zinc-300">
          {(content.items || []).map((item, i) => (
            <span
              key={i}
              className={`cursor-pointer ${getLinkHoverClasses()} ${
                !isLinkHovered ? "hover:text-indigo-400" : ""
              }`}
            >
              {item.title}
            </span>
          ))}
        </nav>

        <button
          className={`px-4 py-1.5 rounded-full text-xs font-semibold text-white shadow-md ${getButtonHoverClasses(
            true
          )}`}
          style={{ backgroundColor: themeConfig.primaryColor || "#2563eb" }}
        >
          {content.primaryBtnText || "Liên Hệ"}
        </button>
      </header>
    );
  }

  // Hero Block
  if (type === "hero") {
    return (
      <section
        className={`w-full px-6 ${styles.paddingTop || "pt-20"} ${styles.paddingBottom || "pb-20"} ${
          styles.bgColor || "bg-gradient-to-b from-[#0A0A0C] via-[#121217] to-[#181824]"
        } ${styles.textColor || "text-zinc-100"} text-center`}
      >
        <div className="max-w-3xl mx-auto space-y-5">
          {content.badge && (
            <div
              className={`inline-flex items-center gap-1.5 px-3.5 py-1 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/30 transition-all ${
                isButtonHovered ? "scale-105 border-indigo-400 bg-indigo-500/20" : ""
              }`}
            >
              <span>{content.badge}</span>
            </div>
          )}

          <h1
            className="text-3xl sm:text-4xl md:text-5xl font-black tracking-tight text-zinc-100 leading-tight"
            style={{ fontFamily: themeConfig.fontHeading }}
          >
            {content.title || "Tiêu đề trang nổi bật"}
          </h1>

          <p className="text-sm sm:text-base text-zinc-300 max-w-xl mx-auto leading-relaxed">
            {content.subtitle || content.description}
          </p>

          <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
            {content.primaryBtnText && (
              <button
                className={`px-6 py-2.5 rounded-full text-xs font-bold text-white shadow-lg ${getButtonHoverClasses(
                  true
                )}`}
                style={{ backgroundColor: themeConfig.primaryColor || "#2563eb" }}
              >
                {content.primaryBtnText}
              </button>
            )}
            {content.secondaryBtnText && (
              <button
                className={`px-6 py-2.5 rounded-full text-xs font-bold text-zinc-200 bg-white/10 border border-white/20 ${getButtonHoverClasses(
                  false
                )}`}
              >
                {content.secondaryBtnText}
              </button>
            )}
          </div>

          {content.imageUrl && (
            <div className="pt-8 max-w-2xl mx-auto">
              <div
                className={`rounded-2xl overflow-hidden border border-white/[0.1] shadow-2xl transition-all ${
                  isCardHovered ? "border-indigo-500/60 shadow-indigo-500/20 translate-y-[-4px]" : ""
                }`}
              >
                <img
                  src={content.imageUrl}
                  alt={content.imageAlt || "Preview"}
                  className={`w-full h-auto object-cover max-h-72 ${getImageHoverClasses()}`}
                  referrerPolicy="no-referrer"
                />
              </div>
            </div>
          )}
        </div>
      </section>
    );
  }

  // Features Block
  if (type === "features") {
    return (
      <section
        className={`w-full px-6 ${styles.paddingTop || "pt-16"} ${styles.paddingBottom || "pb-16"} ${
          styles.bgColor || "bg-[#0A0A0C]"
        } ${styles.textColor || "text-zinc-100"}`}
      >
        <div className="max-w-5xl mx-auto">
          <div className="text-center max-w-xl mx-auto mb-12 space-y-2">
            {content.badge && (
              <span className="text-[11px] font-bold text-indigo-400 tracking-wider uppercase">
                {content.badge}
              </span>
            )}
            <h2
              className="text-2xl sm:text-3xl font-extrabold text-zinc-100"
              style={{ fontFamily: themeConfig.fontHeading }}
            >
              {content.title || "Tính Năng Nổi Bật"}
            </h2>
            <p className="text-xs sm:text-sm text-zinc-400">{content.subtitle}</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {(content.items || []).map((item, i) => (
              <div
                key={i}
                className={`p-6 rounded-2xl bg-[#121217] border border-white/[0.08] space-y-3 ${getCardHoverClasses()} ${
                  !isCardHovered ? "hover:border-indigo-500/40" : ""
                }`}
              >
                <div
                  className={`w-10 h-10 rounded-xl flex items-center justify-center text-white font-bold text-sm shadow-md ${
                    isButtonHovered ? "scale-110 rotate-3 shadow-indigo-500/30" : ""
                  }`}
                  style={{ backgroundColor: themeConfig.primaryColor || "#2563eb" }}
                >
                  ✓
                </div>
                <h3 className="text-base font-bold text-zinc-100">{item.title}</h3>
                <p className="text-xs text-zinc-400 leading-relaxed">{item.desc}</p>
                {item.tag && (
                  <span
                    className={`inline-block text-[10px] font-semibold px-2 py-0.5 rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 ${
                      isButtonHovered ? "bg-indigo-500/25 border-indigo-400" : ""
                    }`}
                  >
                    {item.tag}
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>
    );
  }

  // WooCommerce Product Grid
  if (type === "ecommerce") {
    return (
      <section
        className={`w-full px-6 ${styles.paddingTop || "pt-16"} ${styles.paddingBottom || "pb-16"} ${
          styles.bgColor || "bg-[#0A0A0C]"
        } ${styles.textColor || "text-zinc-100"}`}
      >
        <div className="max-w-5xl mx-auto">
          <div className="text-center max-w-xl mx-auto mb-12 space-y-2">
            {content.badge && (
              <span className="text-[11px] font-bold text-emerald-400 tracking-wider uppercase">
                {content.badge}
              </span>
            )}
            <h2
              className="text-2xl sm:text-3xl font-extrabold text-zinc-100"
              style={{ fontFamily: themeConfig.fontHeading }}
            >
              {content.title || "Sản Phẩm WooCommerce"}
            </h2>
            <p className="text-xs sm:text-sm text-zinc-400">{content.subtitle}</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            {(content.items || []).map((prod, i) => (
              <div
                key={i}
                className={`rounded-2xl bg-[#121217] border border-white/[0.08] overflow-hidden flex flex-col justify-between group/card ${getCardHoverClasses()} ${
                  !isCardHovered ? "hover:border-emerald-500/50" : ""
                }`}
              >
                {prod.image && (
                  <div className="relative h-44 overflow-hidden bg-[#181822]">
                    <img
                      src={prod.image}
                      alt={prod.title}
                      className={`w-full h-full object-cover ${getImageHoverClasses()} ${
                        !isImageHovered ? "group-hover/card:scale-105" : ""
                      }`}
                      referrerPolicy="no-referrer"
                    />
                    {prod.tag && (
                      <span
                        className={`absolute top-3 left-3 px-2 py-0.5 rounded-full bg-rose-500 text-white text-[10px] font-bold uppercase shadow-md ${
                          isButtonHovered ? "scale-105" : ""
                        }`}
                      >
                        {prod.tag}
                      </span>
                    )}
                  </div>
                )}
                <div className="p-4 space-y-2 flex-1 flex flex-col justify-between">
                  <div>
                    <h3
                      className={`text-sm font-bold transition-colors ${
                        isCardHovered || isLinkHovered
                          ? "text-emerald-400"
                          : "text-zinc-100 group-hover/card:text-emerald-400"
                      }`}
                    >
                      {prod.title}
                    </h3>
                    <p className="text-[11px] text-zinc-400 line-clamp-2 mt-1">{prod.desc}</p>
                  </div>
                  <div className="pt-3 border-t border-white/[0.08] flex items-center justify-between">
                    <span className="text-sm font-extrabold text-emerald-400">{prod.price}</span>
                    <button
                      className={`flex items-center gap-1 px-3 py-1 rounded-xl bg-emerald-600 text-white text-[11px] font-bold shadow-md ${getButtonHoverClasses(
                        true
                      )}`}
                    >
                      <ShoppingBag className="w-3 h-3" />
                      <span>{prod.linkText || "Mua Ngay"}</span>
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    );
  }

  // Pricing Block
  if (type === "pricing") {
    return (
      <section
        className={`w-full px-6 ${styles.paddingTop || "pt-16"} ${styles.paddingBottom || "pb-16"} ${
          styles.bgColor || "bg-[#0A0A0C]"
        } ${styles.textColor || "text-zinc-100"}`}
      >
        <div className="max-w-5xl mx-auto">
          <div className="text-center max-w-xl mx-auto mb-12 space-y-2">
            {content.badge && (
              <span className="text-[11px] font-bold text-indigo-400 tracking-wider uppercase">
                {content.badge}
              </span>
            )}
            <h2
              className="text-2xl sm:text-3xl font-extrabold text-zinc-100"
              style={{ fontFamily: themeConfig.fontHeading }}
            >
              {content.title || "Bảng Giá Dịch Vụ"}
            </h2>
            <p className="text-xs sm:text-sm text-zinc-400">{content.subtitle}</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {(content.items || []).map((plan, i) => (
              <div
                key={i}
                className={`p-6 rounded-2xl flex flex-col justify-between ${
                  plan.highlight
                    ? `bg-[#181822] border-2 border-indigo-500 shadow-2xl shadow-indigo-500/20 ${
                        isCardHovered ? "scale-105 ring-4 ring-indigo-500/30" : ""
                      }`
                    : `bg-[#121217] border border-white/[0.08] ${getCardHoverClasses()}`
                }`}
              >
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <h3 className="text-base font-bold text-zinc-100">{plan.title}</h3>
                    {plan.tag && (
                      <span className="text-[9px] font-extrabold px-2 py-0.5 rounded-full bg-indigo-500/20 text-indigo-400 border border-indigo-500/30">
                        {plan.tag}
                      </span>
                    )}
                  </div>

                  <div className="text-2xl font-black text-zinc-100 my-3">
                    {plan.price}
                    <span className="text-xs font-normal text-zinc-400 ml-1">{plan.period || "/tháng"}</span>
                  </div>

                  <p className="text-xs text-zinc-400 mb-4">{plan.desc}</p>
                </div>

                <button
                  className={`w-full py-2 rounded-xl text-xs font-bold ${
                    plan.highlight
                      ? `bg-indigo-600 text-white shadow-lg ${getButtonHoverClasses(true)}`
                      : `bg-[#181822] text-zinc-200 border border-white/[0.08] ${getButtonHoverClasses(false)}`
                  }`}
                >
                  {plan.linkText || "Chọn Gói"}
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>
    );
  }

  // Testimonials Block
  if (type === "testimonials") {
    return (
      <section
        className={`w-full px-6 ${styles.paddingTop || "pt-16"} ${styles.paddingBottom || "pb-16"} ${
          styles.bgColor || "bg-[#0A0A0C]"
        } ${styles.textColor || "text-zinc-100"}`}
      >
        <div className="max-w-4xl mx-auto">
          <div className="text-center max-w-xl mx-auto mb-10 space-y-2">
            <span className="text-[11px] font-bold text-pink-400 tracking-wider uppercase">
              {content.badge || "ĐÁNH GIÁ"}
            </span>
            <h2
              className="text-2xl sm:text-3xl font-extrabold text-zinc-100"
              style={{ fontFamily: themeConfig.fontHeading }}
            >
              {content.title || "Khách Hàng Nói Gì Về Chúng Tôi"}
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {(content.items || []).map((review, i) => (
              <div
                key={i}
                className={`p-6 rounded-2xl bg-[#121217] border border-white/[0.08] space-y-4 ${getCardHoverClasses()}`}
              >
                <div className="flex items-center gap-1 text-amber-400">
                  {[...Array(review.rating || 5)].map((_, idx) => (
                    <Star
                      key={idx}
                      className={`w-3.5 h-3.5 fill-amber-400 ${
                        isButtonHovered ? "scale-110 transition-transform" : ""
                      }`}
                    />
                  ))}
                </div>
                <p className="text-xs sm:text-sm text-zinc-300 italic leading-relaxed">
                  {review.desc || review.title}
                </p>
                <div className="flex items-center gap-3 pt-2 border-t border-white/[0.08]">
                  {review.authorAvatar && (
                    <img
                      src={review.authorAvatar}
                      alt={review.authorName}
                      className={`w-9 h-9 rounded-full object-cover ${getImageHoverClasses()}`}
                      referrerPolicy="no-referrer"
                    />
                  )}
                  <div>
                    <h4 className="text-xs font-bold text-zinc-100">{review.authorName}</h4>
                    <p className="text-[11px] text-zinc-400">{review.authorRole}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    );
  }

  // CTA Block
  if (type === "cta") {
    return (
      <section
        className={`w-full px-6 ${styles.paddingTop || "pt-16"} ${styles.paddingBottom || "pb-16"} ${
          styles.bgColor || "bg-gradient-to-r from-indigo-700 via-indigo-600 to-purple-800"
        } text-white text-center`}
      >
        <div className="max-w-2xl mx-auto space-y-4">
          {content.badge && (
            <span
              className={`text-[11px] font-bold uppercase tracking-wider text-indigo-200 bg-white/10 px-3 py-1 rounded-full ${
                isButtonHovered ? "scale-105 bg-white/20 text-white" : ""
              }`}
            >
              {content.badge}
            </span>
          )}
          <h2
            className="text-2xl sm:text-3xl font-black text-white"
            style={{ fontFamily: themeConfig.fontHeading }}
          >
            {content.title}
          </h2>
          <p className="text-xs sm:text-sm text-indigo-100 max-w-lg mx-auto">{content.subtitle}</p>
          <div className="pt-2 flex flex-wrap justify-center gap-3">
            <button
              className={`px-6 py-2.5 rounded-full bg-white text-indigo-600 text-xs font-bold shadow-xl ${getButtonHoverClasses(
                false
              )}`}
            >
              {content.primaryBtnText || "Bắt Đầu Ngay"}
            </button>
          </div>
        </div>
      </section>
    );
  }

  // FAQ Block
  if (type === "faq") {
    return (
      <section
        className={`w-full px-6 ${styles.paddingTop || "pt-16"} ${styles.paddingBottom || "pb-16"} ${
          styles.bgColor || "bg-[#0A0A0C]"
        } ${styles.textColor || "text-zinc-100"}`}
      >
        <div className="max-w-3xl mx-auto space-y-6">
          <div className="text-center space-y-2">
            <h2
              className="text-2xl font-extrabold text-zinc-100"
              style={{ fontFamily: themeConfig.fontHeading }}
            >
              {content.title || "Câu Hỏi Thường Gặp"}
            </h2>
            <p className="text-xs sm:text-sm text-zinc-400">{content.subtitle}</p>
          </div>

          <div className="space-y-3">
            {(content.items || []).map((faq, i) => (
              <div
                key={i}
                className={`p-4 rounded-2xl bg-[#121217] border border-white/[0.08] space-y-2 ${getCardHoverClasses()}`}
              >
                <div className="flex items-center justify-between font-bold text-xs text-zinc-100">
                  <span className={isLinkHovered ? "text-indigo-400" : ""}>{faq.title}</span>
                  <ChevronDown
                    className={`w-4 h-4 text-zinc-400 ${
                      isButtonHovered || isCardHovered ? "rotate-180 text-indigo-400 transition-transform" : ""
                    }`}
                  />
                </div>
                <p className="text-xs text-zinc-400 leading-relaxed">{faq.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    );
  }

  // Stats Block
  if (type === "stats") {
    return (
      <section
        className={`w-full px-6 py-12 ${styles.bgColor || "bg-[#121217]"} ${
          styles.textColor || "text-zinc-100"
        } border-y border-white/[0.08]`}
      >
        <div className="max-w-4xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
          {(content.items || []).map((stat, i) => (
            <div
              key={i}
              className={`space-y-1 p-3 rounded-xl transition-all ${
                isCardHovered ? "bg-[#181824] shadow-md scale-105" : ""
              }`}
            >
              <div
                className={`text-2xl sm:text-3xl font-black text-indigo-400 ${
                  isButtonHovered ? "scale-110 text-amber-400 transition-transform" : ""
                }`}
              >
                {stat.title}
              </div>
              <div className="text-xs text-zinc-400">{stat.desc}</div>
            </div>
          ))}
        </div>
      </section>
    );
  }

  // Footer Block
  if (type === "footer") {
    return (
      <footer
        className={`w-full px-6 py-12 ${styles.bgColor || "bg-[#0A0A0C] border-t border-white/[0.08]"} ${
          styles.textColor || "text-zinc-400"
        } text-xs`}
      >
        <div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          <div>
            <h3 className="font-bold text-zinc-100 text-sm mb-2">{content.title || "WP Studio"}</h3>
            <p className="text-zinc-400 leading-relaxed">{content.description}</p>
          </div>
          <div>
            <h4 className="font-semibold text-zinc-100 mb-2">Liên Kết Nhanh</h4>
            <div className="space-y-1 text-zinc-400">
              <div className={`cursor-pointer ${getLinkHoverClasses()}`}>Trang Chủ</div>
              <div className={`cursor-pointer ${getLinkHoverClasses()}`}>Về Chúng Tôi</div>
              <div className={`cursor-pointer ${getLinkHoverClasses()}`}>Bảng Giá</div>
            </div>
          </div>
          <div>
            <h4 className="font-semibold text-zinc-100 mb-2">Bản Quyền</h4>
            <p className="text-zinc-500">{content.copyrightText || "© 2026 WP Studio. All rights reserved."}</p>
          </div>
        </div>
      </footer>
    );
  }

  // Custom / Fallback Block
  return (
    <section className={`w-full px-6 py-12 ${styles.bgColor || "bg-[#121217]"} text-zinc-100 text-center`}>
      <div className="max-w-xl mx-auto space-y-2">
        <h3 className="text-lg font-bold text-zinc-100">{content.title || block.name}</h3>
        <p className="text-xs text-zinc-400">{content.subtitle || content.description}</p>
        {content.rawHtml && (
          <div
            className="mt-4 p-4 rounded-xl bg-[#0A0A0C] border border-white/[0.08] text-left text-xs"
            dangerouslySetInnerHTML={{ __html: content.rawHtml }}
          />
        )}
      </div>
    </section>
  );
};

